const BOXNO_00 = {
    '18060124': [{
            lockerBoxId: 1,
            lockerId: '18060124',
            boxNo: '001'
        },
        {
            lockerBoxId: 2,
            lockerId: '18060124',
            boxNo: '002'
        },
        {
            lockerBoxId: 3,
            lockerId: '18060124',
            boxNo: '003'
        },
        {
            lockerBoxId: 4,
            lockerId: '18060124',
            boxNo: '004'
        },
        {
            lockerBoxId: 5,
            lockerId: '18060124',
            boxNo: '005'
        },
        {
            lockerBoxId: 6,
            lockerId: '18060124',
            boxNo: '006'
        },
        {
            lockerBoxId: 7,
            lockerId: '18060124',
            boxNo: '007'
        },
        {
            lockerBoxId: 8,
            lockerId: '18060124',
            boxNo: '008'
        },
        {
            lockerBoxId: 9,
            lockerId: '18060124',
            boxNo: '009'
        },
        {
            lockerBoxId: 10,
            lockerId: '18060124',
            boxNo: '010'
        },
        {
            lockerBoxId: 11,
            lockerId: '18060124',
            boxNo: '011',
        },
        {
            lockerBoxId: 12,
            lockerId: '18060124',
            boxNo: '012'
        },
        {
            lockerBoxId: 13,
            lockerId: '18060124',
            boxNo: '013'
        },
        {
            lockerBoxId: 14,
            lockerId: '18060124',
            boxNo: '014'
        },
        {
            lockerBoxId: 15,
            lockerId: '18060124',
            boxNo: '015'
        },
        {
            lockerBoxId: 16,
            lockerId: '18060124',
            boxNo: '016'
        },
        {
            lockerBoxId: 17,
            lockerId: '18060124',
            boxNo: '017'
        },
        {
            lockerBoxId: 18,
            lockerId: '18060124',
            boxNo: '018'
        },
        {
            lockerBoxId: 19,
            lockerId: '18060124',
            boxNo: '019'
        },
        {
            lockerBoxId: 20,
            lockerId: '18060124',
            boxNo: '020'
        },
        {
            lockerBoxId: 21,
            lockerId: '18060124',
            boxNo: '021'
        },
        {
            lockerBoxId: 22,
            lockerId: '18060124',
            boxNo: '022'
        },
        {
            lockerBoxId: 23,
            lockerId: '18060124',
            boxNo: '023',
        },
        {
            lockerBoxId: 24,
            lockerId: '18060124',
            boxNo: '024',
        }
    ],
    '18060121': [{
            lockerBoxId: 25,
            lockerId: '18060121',
            boxNo: '001',
        },
        {
            lockerBoxId: 26,
            lockerId: '18060121',
            boxNo: '002',
        },
        {
            lockerBoxId: 27,
            lockerId: '18060121',
            boxNo: '003',
        },
        {
            lockerBoxId: 28,
            lockerId: '18060121',
            boxNo: '004',
        },
        {
            lockerBoxId: 29,
            lockerId: '18060121',
            boxNo: '005',
        },
        {
            lockerBoxId: 30,
            lockerId: '18060121',
            boxNo: '006',
        },
        {
            lockerBoxId: 31,
            lockerId: '18060121',
            boxNo: '007',
        },
        {
            lockerBoxId: 32,
            lockerId: '18060121',
            boxNo: '008',
        },
        {
            lockerBoxId: 33,
            lockerId: '18060121',
            boxNo: '009',
        },
        {
            lockerBoxId: 34,
            lockerId: '18060121',
            boxNo: '010',
        },
        {
            lockerBoxId: 35,
            lockerId: '18060121',
            boxNo: '011',
        },
        {
            lockerBoxId: 36,
            lockerId: '18060121',
            boxNo: '012',
        },
        {
            lockerBoxId: 37,
            lockerId: '18060121',
            boxNo: '013',
        },
        {
            lockerBoxId: 38,
            lockerId: '18060121',
            boxNo: '014',
        },
        {
            lockerBoxId: 39,
            lockerId: '18060121',
            boxNo: '015',
        },
        {
            lockerBoxId: 40,
            lockerId: '18060121',
            boxNo: '016',
        },
        {
            lockerBoxId: 41,
            lockerId: '18060121',
            boxNo: '017',
        },
        {
            lockerBoxId: 42,
            lockerId: '18060121',
            boxNo: '018',
        },
        {
            lockerBoxId: 43,
            lockerId: '18060121',
            boxNo: '019',
        },
        {
            lockerBoxId: 44,
            lockerId: '18060121',
            boxNo: '020',
        },
        {
            lockerBoxId: 45,
            lockerId: '18060121',
            boxNo: '021',
        },
        {
            lockerBoxId: 46,
            lockerId: '18060121',
            boxNo: '022',
        },
        {
            lockerBoxId: 47,
            lockerId: '18060121',
            boxNo: '023',
        },
        {
            lockerBoxId: 48,
            lockerId: '18060121',
            boxNo: '024',
        }
    ],
    '18120246': [{
            lockerBoxId: 49,
            lockerId: '18120246',
            boxNo: '001',
        },
        {
            lockerBoxId: 50,
            lockerId: '18120246',
            boxNo: '002',
        },
        {
            lockerBoxId: 51,
            lockerId: '18120246',
            boxNo: '003',
        },
        {
            lockerBoxId: 52,
            lockerId: '18120246',
            boxNo: '004',
        },
        {
            lockerBoxId: 53,
            lockerId: '18120246',
            boxNo: '005',
        },
        {
            lockerBoxId: 54,
            lockerId: '18120246',
            boxNo: '006',
        },
        {
            lockerBoxId: 55,
            lockerId: '18120246',
            boxNo: '007',
        },
        {
            lockerBoxId: 56,
            lockerId: '18120246',
            boxNo: '008',
        },
        {
            lockerBoxId: 57,
            lockerId: '18120246',
            boxNo: '009',
        },
        {
            lockerBoxId: 58,
            lockerId: '18120246',
            boxNo: '010',
        },
        {
            lockerBoxId: 59,
            lockerId: '18120246',
            boxNo: '011',
        },
        {
            lockerBoxId: 60,
            lockerId: '18120246',
            boxNo: '012',
        },
        {
            lockerBoxId: 61,
            lockerId: '18120246',
            boxNo: '013',
        },
        {
            lockerBoxId: 62,
            lockerId: '18120246',
            boxNo: '014',
        },
        {
            lockerBoxId: 63,
            lockerId: '18120246',
            boxNo: '015',
        },
        {
            lockerBoxId: 64,
            lockerId: '18120246',
            boxNo: '016',
        },
        {
            lockerBoxId: 65,
            lockerId: '18120246',
            boxNo: '017',
        },
        {
            lockerBoxId: 66,
            lockerId: '18120246',
            boxNo: '018',
        },
        {
            lockerBoxId: 67,
            lockerId: '18120246',
            boxNo: '019',
        },
        {
            lockerBoxId: 68,
            lockerId: '18120246',
            boxNo: '020',
        },
        {
            lockerBoxId: 69,
            lockerId: '18120246',
            boxNo: '021',
        },
        {
            lockerBoxId: 70,
            lockerId: '18120246',
            boxNo: '022',
        },
        {
            lockerBoxId: 71,
            lockerId: '18120246',
            boxNo: '023',
        },
        {
            lockerBoxId: 72,
            lockerId: '18120246',
            boxNo: '024',
        }
    ],
    '18120242': [{
            lockerBoxId: 73,
            lockerId: '18120242',
            boxNo: '001',
        },
        {
            lockerBoxId: 74,
            lockerId: '18120242',
            boxNo: '002',
        },
        {
            lockerBoxId: 75,
            lockerId: '18120242',
            boxNo: '003',
        },
        {
            lockerBoxId: 76,
            lockerId: '18120242',
            boxNo: '004',
        },
        {
            lockerBoxId: 77,
            lockerId: '18120242',
            boxNo: '005',
        },
        {
            lockerBoxId: 78,
            lockerId: '18120242',
            boxNo: '006',
        },
        {
            lockerBoxId: 79,
            lockerId: '18120242',
            boxNo: '007',
        },
        {
            lockerBoxId: 80,
            lockerId: '18120242',
            boxNo: '008',
        },
        {
            lockerBoxId: 81,
            lockerId: '18120242',
            boxNo: '009',
        },
        {
            lockerBoxId: 82,
            lockerId: '18120242',
            boxNo: '010',
        },
        {
            lockerBoxId: 83,
            lockerId: '18120242',
            boxNo: '011',
        },
        {
            lockerBoxId: 84,
            lockerId: '18120242',
            boxNo: '012',
        },
        {
            lockerBoxId: 85,
            lockerId: '18120242',
            boxNo: '013',
        },
        {
            lockerBoxId: 86,
            lockerId: '18120242',
            boxNo: '014',
        },
        {
            lockerBoxId: 87,
            lockerId: '18120242',
            boxNo: '015',
        },
        {
            lockerBoxId: 88,
            lockerId: '18120242',
            boxNo: '016',
        },
        {
            lockerBoxId: 89,
            lockerId: '18120242',
            boxNo: '017',
        },
        {
            lockerBoxId: 90,
            lockerId: '18120242',
            boxNo: '018',
        },
        {
            lockerBoxId: 91,
            lockerId: '18120242',
            boxNo: '019',
        },
        {
            lockerBoxId: 92,
            lockerId: '18120242',
            boxNo: '020',
        },
        {
            lockerBoxId: 93,
            lockerId: '18120242',
            boxNo: '021',
        },
        {
            lockerBoxId: 94,
            lockerId: '18120242',
            boxNo: '022',
        },
        {
            lockerBoxId: 95,
            lockerId: '18120242',
            boxNo: '023',
        },
        {
            lockerBoxId: 96,
            lockerId: '18120242',
            boxNo: '024',
        }
    ],
    '18060117': [{
            lockerBoxId: 97,
            lockerId: '18060117',
            boxNo: '001',
        },
        {
            lockerBoxId: 98,
            lockerId: '18060117',
            boxNo: '002',
        },
        {
            lockerBoxId: 99,
            lockerId: '18060117',
            boxNo: '003',
        },
        {
            lockerBoxId: 100,
            lockerId: '18060117',
            boxNo: '004',
        },
        {
            lockerBoxId: 101,
            lockerId: '18060117',
            boxNo: '005',
        },
        {
            lockerBoxId: 102,
            lockerId: '18060117',
            boxNo: '006',
        },
        {
            lockerBoxId: 103,
            lockerId: '18060117',
            boxNo: '007',
        },
        {
            lockerBoxId: 104,
            lockerId: '18060117',
            boxNo: '008',
        },
        {
            lockerBoxId: 105,
            lockerId: '18060117',
            boxNo: '009',
        },
        {
            lockerBoxId: 106,
            lockerId: '18060117',
            boxNo: '010',
        },
        {
            lockerBoxId: 107,
            lockerId: '18060117',
            boxNo: '011',
        },
        {
            lockerBoxId: 108,
            lockerId: '18060117',
            boxNo: '012',
        },
        {
            lockerBoxId: 109,
            lockerId: '18060117',
            boxNo: '013',
        },
        {
            lockerBoxId: 110,
            lockerId: '18060117',
            boxNo: '014',
        },
        {
            lockerBoxId: 111,
            lockerId: '18060117',
            boxNo: '015',
        },
        {
            lockerBoxId: 112,
            lockerId: '18060117',
            boxNo: '016',
        },
        {
            lockerBoxId: 113,
            lockerId: '18060117',
            boxNo: '017',
        },
        {
            lockerBoxId: 114,
            lockerId: '18060117',
            boxNo: '018',
        },
        {
            lockerBoxId: 115,
            lockerId: '18060117',
            boxNo: '019',
        },
        {
            lockerBoxId: 116,
            lockerId: '18060117',
            boxNo: '020',
        },
        {
            lockerBoxId: 117,
            lockerId: '18060117',
            boxNo: '021',
        },
        {
            lockerBoxId: 118,
            lockerId: '18060117',
            boxNo: '022',
        },
        {
            lockerBoxId: 119,
            lockerId: '18060117',
            boxNo: '023',
        },
        {
            lockerBoxId: 120,
            lockerId: '18060117',
            boxNo: '024',
        }
    ],
    '18060179': [{
            lockerBoxId: 121,
            lockerId: '18060179',
            boxNo: '001',
        },
        {
            lockerBoxId: 122,
            lockerId: '18060179',
            boxNo: '002',
        },
        {
            lockerBoxId: 123,
            lockerId: '18060179',
            boxNo: '003',
        },
        {
            lockerBoxId: 124,
            lockerId: '18060179',
            boxNo: '004',
        },
        {
            lockerBoxId: 125,
            lockerId: '18060179',
            boxNo: '005',
        },
        {
            lockerBoxId: 126,
            lockerId: '18060179',
            boxNo: '006',
        },
        {
            lockerBoxId: 127,
            lockerId: '18060179',
            boxNo: '007',
        },
        {
            lockerBoxId: 128,
            lockerId: '18060179',
            boxNo: '008',
        },
        {
            lockerBoxId: 129,
            lockerId: '18060179',
            boxNo: '009',
        },
        {
            lockerBoxId: 130,
            lockerId: '18060179',
            boxNo: '010',
        },
        {
            lockerBoxId: 131,
            lockerId: '18060179',
            boxNo: '011',
        },
        {
            lockerBoxId: 132,
            lockerId: '18060179',
            boxNo: '012',
        },
        {
            lockerBoxId: 133,
            lockerId: '18060179',
            boxNo: '013',
        },
        {
            lockerBoxId: 134,
            lockerId: '18060179',
            boxNo: '014',
        },
        {
            lockerBoxId: 135,
            lockerId: '18060179',
            boxNo: '015',
        },
        {
            lockerBoxId: 136,
            lockerId: '18060179',
            boxNo: '016',
        },
        {
            lockerBoxId: 137,
            lockerId: '18060179',
            boxNo: '017',
        },
        {
            lockerBoxId: 138,
            lockerId: '18060179',
            boxNo: '018',
        },
        {
            lockerBoxId: 139,
            lockerId: '18060179',
            boxNo: '019',
        },
        {
            lockerBoxId: 140,
            lockerId: '18060179',
            boxNo: '020',
        },
        {
            lockerBoxId: 141,
            lockerId: '18060179',
            boxNo: '021',
        },
        {
            lockerBoxId: 142,
        },
        {
            lockerBoxId: 144,
            lockerId: '18060179',
            boxNo: '024',
        }
    ],
    '18120245': [{
            lockerBoxId: 145,
            lockerId: '18120245',
            boxNo: '001',
        },
        {
            lockerBoxId: 146,
            lockerId: '18120245',
            boxNo: '002',
        },
        {
            lockerBoxId: 147,
            lockerId: '18120245',
            boxNo: '003',
        },
        {
            lockerBoxId: 148,
            lockerId: '18120245',
            boxNo: '004',
        },
        {
            lockerBoxId: 149,
            lockerId: '18120245',
            boxNo: '005',
        },
        {
            lockerBoxId: 150,
            lockerId: '18120245',
            boxNo: '006',
        },
        {
            lockerBoxId: 151,
            lockerId: '18120245',
            boxNo: '007',
        },
        {
            lockerBoxId: 152,
            lockerId: '18120245',
            boxNo: '008',
        },
        {
            lockerBoxId: 153,
            lockerId: '18120245',
            boxNo: '009',
        },
        {
            lockerBoxId: 154,
            lockerId: '18120245',
            boxNo: '010',
        },
        {
            lockerBoxId: 155,
            lockerId: '18120245',
            boxNo: '011',
        },
        {
            lockerBoxId: 156,
            lockerId: '18120245',
            boxNo: '012',
        },
        {
            lockerBoxId: 157,
            lockerId: '18120245',
            boxNo: '013',
        },
        {
            lockerBoxId: 158,
            lockerId: '18120245',
            boxNo: '014',
        },
        {
            lockerBoxId: 159,
            lockerId: '18120245',
            boxNo: '015',
        },
        {
            lockerBoxId: 160,
            lockerId: '18120245',
            boxNo: '016',
        },
        {
            lockerBoxId: 161,
            lockerId: '18120245',
            boxNo: '017',
        },
        {
            lockerBoxId: 162,
            lockerId: '18120245',
            boxNo: '018',
        },
        {
            lockerBoxId: 163,
            lockerId: '18120245',
            boxNo: '019',
        },
        {
            lockerBoxId: 164,
            lockerId: '18120245',
            boxNo: '020',
        },
        {
            lockerBoxId: 165,
            lockerId: '18120245',
            boxNo: '021',
        },
        {
            lockerBoxId: 166,
            lockerId: '18120245',
            boxNo: '022',
        },
        {
            lockerBoxId: 167,
            lockerId: '18120245',
            boxNo: '023',
        },
        {
            lockerBoxId: 168,
            lockerId: '18120245',
            boxNo: '024',
        }
    ]
}
module.exports = BOXNO_00