// 0003<四楼> 柜号

const LOCKERNO_0003 = [{
        lockerId: '19060080',
        lockerAddress: '192.168.2.108',
        boxNum: '024',
        lockerNo: '0008',
        areaNo: '0003',
    },
    {
        lockerId: '18120247',
        lockerAddress: '192.168.2.109',
        boxNum: '024',
        lockerNo: '0009',
        areaNo: '0003',
    },
    {
        lockerId: '18120235',
        lockerAddress: '192.168.2.110',
        boxNum: '024',
        lockerNo: '0010',
        areaNo: '0003',
    },
    {
        lockerId: '18120243',
        lockerAddress: '192.168.2.111',
        boxNum: '024',
        lockerNo: '0011',
        areaNo: '0003',
    },
    {
        lockerId: '18060182',
        lockerAddress: '192.168.2.112',
        boxNum: '024',
        lockerNo: '0012',
        areaNo: '0003',
        note: '88',
    },
    {
        lockerId: '18120241',
        lockerAddress: '192.168.2.113',
        boxNum: '024',
        lockerNo: '0013',
        areaNo: '0003',
        note: '88',
    },
    {
        lockerId: '18060183',
        lockerAddress: '192.168.2.114',
        boxNum: '024',
        lockerNo: '0014',
        areaNo: '0003',
        note: '88',
    }
]

module.exports = LOCKERNO_0003