// 00<三楼> 柜号

const LOCKERNO_00 = [{
        lockerId: '18060124',
        lockerAddress: '192.168.2.101',
        boxNum: '024',
        lockerNo: '0001',
        areaNo: '00',
    },
    {
        lockerId: '18060121',
        lockerAddress: '192.168.2.102',
        boxNum: '024',
        lockerNo: '0002',
        areaNo: '00',
    },
    {
        lockerId: '18120246',
        lockerAddress: '192.168.2.103',
        boxNum: '024',
        lockerNo: '0003',
        areaNo: '00',
    },
    {
        lockerId: '18120242',
        lockerAddress: '192.168.2.104',
        boxNum: '024',
        lockerNo: '0004',
        areaNo: '00',
    },
    {
        lockerId: '18060117',
        lockerAddress: '192.168.2.105',
        boxNum: '024',
        lockerNo: '0005',
        areaNo: '00',
    },
    {
        lockerId: '18060179',
        lockerAddress: '192.168.2.106',
        boxNum: '024',
        lockerNo: '0006',
        areaNo: '00',
    },
    {
        lockerId: '18120245',
        lockerAddress: '192.168.2.107',
        boxNum: '024',
        lockerNo: '0007',
        areaNo: '00',
    }
]

module.exports = LOCKERNO_00