// 0004<五楼> 柜号

const LOCKERNO_0004 = [{
        lockerId: '18060181',
        lockerAddress: '192.168.2.115',
        boxNum: '024',
        lockerNo: '0015',
        areaNo: '0004',
    },
    {
        lockerId: '18060180',
        lockerAddress: '192.168.2.116',
        boxNum: '024',
        lockerNo: '0016',
        areaNo: '0004'
    },
    {
        lockerId: '18120238',
        lockerAddress: '192.168.2.117',
        boxNum: '024',
        lockerNo: '0017',
        areaNo: '0004',
    },
    {
        lockerId: '18060119',
        lockerAddress: '192.168.2.118',
        boxNum: '024',
        lockerNo: '0018',
        areaNo: '0004',
        note: '88',
        port: 49153,
        switchesIP: '/192.168.2.118',
        id: '91',
        type: '1',
        state: null,
        boxNum: '024',
        lockerNo: '0017',
        areaNo: '0004',
    },
    {
        lockerId: '18060119',
        lockerAddress: '192.168.2.118',
        boxNum: '024',
        lockerNo: '0018',
        areaNo: '0004'
    },
    {
        lockerId: '18060146',
        lockerAddress: '192.168.2.119',
        boxNum: '024',
        lockerNo: '0019',
        areaNo: '0004'
    }
]

module.exports = LOCKERNO_0004